
namespace CapaPresentacion.Forms
{
    partial class FormCitas
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormCitas));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btn_eliminarCita = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_modificarCita = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_buscarCita = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_registroCita = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dgv_citas = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.txt_telefonoCliente = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_correoCliente = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_nombreCliente = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_identCliente = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.cmb_Doctor = new System.Windows.Forms.ComboBox();
            this.dtp_fechaCita = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.dtp_horaCita = new System.Windows.Forms.DateTimePicker();
            this.CitasElipse = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.txt_descCita = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbl_descCitas = new System.Windows.Forms.Label();
            this.TimeElipse = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_citas)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panel1.Controls.Add(this.btn_eliminarCita);
            this.panel1.Controls.Add(this.btn_modificarCita);
            this.panel1.Controls.Add(this.btn_buscarCita);
            this.panel1.Controls.Add(this.btn_registroCita);
            this.panel1.Controls.Add(this.dgv_citas);
            this.panel1.Location = new System.Drawing.Point(277, 1);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(525, 540);
            this.panel1.TabIndex = 26;
            // 
            // btn_eliminarCita
            // 
            this.btn_eliminarCita.AllowAnimations = true;
            this.btn_eliminarCita.AllowMouseEffects = true;
            this.btn_eliminarCita.AllowToggling = false;
            this.btn_eliminarCita.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_eliminarCita.AnimationSpeed = 200;
            this.btn_eliminarCita.AutoGenerateColors = false;
            this.btn_eliminarCita.AutoRoundBorders = true;
            this.btn_eliminarCita.AutoSizeLeftIcon = true;
            this.btn_eliminarCita.AutoSizeRightIcon = true;
            this.btn_eliminarCita.BackColor = System.Drawing.Color.Transparent;
            this.btn_eliminarCita.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_eliminarCita.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_eliminarCita.BackgroundImage")));
            this.btn_eliminarCita.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminarCita.ButtonText = "Eliminar";
            this.btn_eliminarCita.ButtonTextMarginLeft = 0;
            this.btn_eliminarCita.ColorContrastOnClick = 45;
            this.btn_eliminarCita.ColorContrastOnHover = 45;
            this.btn_eliminarCita.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_eliminarCita.CustomizableEdges = borderEdges5;
            this.btn_eliminarCita.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_eliminarCita.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_eliminarCita.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_eliminarCita.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_eliminarCita.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btn_eliminarCita.Font = new System.Drawing.Font("Montserrat", 8F, System.Drawing.FontStyle.Bold);
            this.btn_eliminarCita.ForeColor = System.Drawing.Color.White;
            this.btn_eliminarCita.IconLeft = null;
            this.btn_eliminarCita.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_eliminarCita.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_eliminarCita.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_eliminarCita.IconMarginLeft = 11;
            this.btn_eliminarCita.IconPadding = 10;
            this.btn_eliminarCita.IconRight = null;
            this.btn_eliminarCita.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_eliminarCita.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_eliminarCita.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_eliminarCita.IconSize = 25;
            this.btn_eliminarCita.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_eliminarCita.IdleBorderRadius = 0;
            this.btn_eliminarCita.IdleBorderThickness = 0;
            this.btn_eliminarCita.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_eliminarCita.IdleIconLeftImage = null;
            this.btn_eliminarCita.IdleIconRightImage = null;
            this.btn_eliminarCita.IndicateFocus = false;
            this.btn_eliminarCita.Location = new System.Drawing.Point(400, 433);
            this.btn_eliminarCita.Name = "btn_eliminarCita";
            this.btn_eliminarCita.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_eliminarCita.OnDisabledState.BorderRadius = 39;
            this.btn_eliminarCita.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminarCita.OnDisabledState.BorderThickness = 1;
            this.btn_eliminarCita.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_eliminarCita.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_eliminarCita.OnDisabledState.IconLeftImage = null;
            this.btn_eliminarCita.OnDisabledState.IconRightImage = null;
            this.btn_eliminarCita.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarCita.onHoverState.BorderRadius = 39;
            this.btn_eliminarCita.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminarCita.onHoverState.BorderThickness = 1;
            this.btn_eliminarCita.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarCita.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminarCita.onHoverState.IconLeftImage = null;
            this.btn_eliminarCita.onHoverState.IconRightImage = null;
            this.btn_eliminarCita.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarCita.OnIdleState.BorderRadius = 39;
            this.btn_eliminarCita.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminarCita.OnIdleState.BorderThickness = 1;
            this.btn_eliminarCita.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarCita.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminarCita.OnIdleState.IconLeftImage = null;
            this.btn_eliminarCita.OnIdleState.IconRightImage = null;
            this.btn_eliminarCita.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarCita.OnPressedState.BorderRadius = 39;
            this.btn_eliminarCita.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminarCita.OnPressedState.BorderThickness = 1;
            this.btn_eliminarCita.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarCita.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminarCita.OnPressedState.IconLeftImage = null;
            this.btn_eliminarCita.OnPressedState.IconRightImage = null;
            this.btn_eliminarCita.Size = new System.Drawing.Size(91, 39);
            this.btn_eliminarCita.TabIndex = 35;
            this.btn_eliminarCita.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_eliminarCita.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_eliminarCita.TextMarginLeft = 0;
            this.btn_eliminarCita.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_eliminarCita.UseDefaultRadiusAndThickness = true;
            this.btn_eliminarCita.Click += new System.EventHandler(this.btn_eliminarCita_Click);
            // 
            // btn_modificarCita
            // 
            this.btn_modificarCita.AllowAnimations = true;
            this.btn_modificarCita.AllowMouseEffects = true;
            this.btn_modificarCita.AllowToggling = false;
            this.btn_modificarCita.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_modificarCita.AnimationSpeed = 200;
            this.btn_modificarCita.AutoGenerateColors = false;
            this.btn_modificarCita.AutoRoundBorders = true;
            this.btn_modificarCita.AutoSizeLeftIcon = true;
            this.btn_modificarCita.AutoSizeRightIcon = true;
            this.btn_modificarCita.BackColor = System.Drawing.Color.Transparent;
            this.btn_modificarCita.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_modificarCita.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_modificarCita.BackgroundImage")));
            this.btn_modificarCita.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_modificarCita.ButtonText = "Modificar";
            this.btn_modificarCita.ButtonTextMarginLeft = 0;
            this.btn_modificarCita.ColorContrastOnClick = 45;
            this.btn_modificarCita.ColorContrastOnHover = 45;
            this.btn_modificarCita.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btn_modificarCita.CustomizableEdges = borderEdges6;
            this.btn_modificarCita.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_modificarCita.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_modificarCita.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_modificarCita.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_modificarCita.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btn_modificarCita.Font = new System.Drawing.Font("Montserrat", 8F, System.Drawing.FontStyle.Bold);
            this.btn_modificarCita.ForeColor = System.Drawing.Color.White;
            this.btn_modificarCita.IconLeft = null;
            this.btn_modificarCita.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_modificarCita.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_modificarCita.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_modificarCita.IconMarginLeft = 11;
            this.btn_modificarCita.IconPadding = 10;
            this.btn_modificarCita.IconRight = null;
            this.btn_modificarCita.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_modificarCita.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_modificarCita.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_modificarCita.IconSize = 25;
            this.btn_modificarCita.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_modificarCita.IdleBorderRadius = 0;
            this.btn_modificarCita.IdleBorderThickness = 0;
            this.btn_modificarCita.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_modificarCita.IdleIconLeftImage = null;
            this.btn_modificarCita.IdleIconRightImage = null;
            this.btn_modificarCita.IndicateFocus = false;
            this.btn_modificarCita.Location = new System.Drawing.Point(303, 433);
            this.btn_modificarCita.Name = "btn_modificarCita";
            this.btn_modificarCita.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_modificarCita.OnDisabledState.BorderRadius = 39;
            this.btn_modificarCita.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_modificarCita.OnDisabledState.BorderThickness = 1;
            this.btn_modificarCita.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_modificarCita.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_modificarCita.OnDisabledState.IconLeftImage = null;
            this.btn_modificarCita.OnDisabledState.IconRightImage = null;
            this.btn_modificarCita.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarCita.onHoverState.BorderRadius = 39;
            this.btn_modificarCita.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_modificarCita.onHoverState.BorderThickness = 1;
            this.btn_modificarCita.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarCita.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_modificarCita.onHoverState.IconLeftImage = null;
            this.btn_modificarCita.onHoverState.IconRightImage = null;
            this.btn_modificarCita.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarCita.OnIdleState.BorderRadius = 39;
            this.btn_modificarCita.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_modificarCita.OnIdleState.BorderThickness = 1;
            this.btn_modificarCita.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarCita.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_modificarCita.OnIdleState.IconLeftImage = null;
            this.btn_modificarCita.OnIdleState.IconRightImage = null;
            this.btn_modificarCita.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarCita.OnPressedState.BorderRadius = 39;
            this.btn_modificarCita.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_modificarCita.OnPressedState.BorderThickness = 1;
            this.btn_modificarCita.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarCita.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_modificarCita.OnPressedState.IconLeftImage = null;
            this.btn_modificarCita.OnPressedState.IconRightImage = null;
            this.btn_modificarCita.Size = new System.Drawing.Size(91, 39);
            this.btn_modificarCita.TabIndex = 34;
            this.btn_modificarCita.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_modificarCita.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_modificarCita.TextMarginLeft = 0;
            this.btn_modificarCita.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_modificarCita.UseDefaultRadiusAndThickness = true;
            this.btn_modificarCita.Click += new System.EventHandler(this.btn_modificarCita_Click);
            // 
            // btn_buscarCita
            // 
            this.btn_buscarCita.AllowAnimations = true;
            this.btn_buscarCita.AllowMouseEffects = true;
            this.btn_buscarCita.AllowToggling = false;
            this.btn_buscarCita.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_buscarCita.AnimationSpeed = 200;
            this.btn_buscarCita.AutoGenerateColors = false;
            this.btn_buscarCita.AutoRoundBorders = true;
            this.btn_buscarCita.AutoSizeLeftIcon = true;
            this.btn_buscarCita.AutoSizeRightIcon = true;
            this.btn_buscarCita.BackColor = System.Drawing.Color.Transparent;
            this.btn_buscarCita.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_buscarCita.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_buscarCita.BackgroundImage")));
            this.btn_buscarCita.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_buscarCita.ButtonText = "Buscar";
            this.btn_buscarCita.ButtonTextMarginLeft = 0;
            this.btn_buscarCita.ColorContrastOnClick = 45;
            this.btn_buscarCita.ColorContrastOnHover = 45;
            this.btn_buscarCita.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn_buscarCita.CustomizableEdges = borderEdges7;
            this.btn_buscarCita.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_buscarCita.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_buscarCita.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_buscarCita.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_buscarCita.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btn_buscarCita.Font = new System.Drawing.Font("Montserrat", 8F, System.Drawing.FontStyle.Bold);
            this.btn_buscarCita.ForeColor = System.Drawing.Color.White;
            this.btn_buscarCita.IconLeft = null;
            this.btn_buscarCita.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_buscarCita.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_buscarCita.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_buscarCita.IconMarginLeft = 11;
            this.btn_buscarCita.IconPadding = 10;
            this.btn_buscarCita.IconRight = null;
            this.btn_buscarCita.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_buscarCita.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_buscarCita.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_buscarCita.IconSize = 25;
            this.btn_buscarCita.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_buscarCita.IdleBorderRadius = 0;
            this.btn_buscarCita.IdleBorderThickness = 0;
            this.btn_buscarCita.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_buscarCita.IdleIconLeftImage = null;
            this.btn_buscarCita.IdleIconRightImage = null;
            this.btn_buscarCita.IndicateFocus = false;
            this.btn_buscarCita.Location = new System.Drawing.Point(206, 433);
            this.btn_buscarCita.Name = "btn_buscarCita";
            this.btn_buscarCita.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_buscarCita.OnDisabledState.BorderRadius = 39;
            this.btn_buscarCita.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_buscarCita.OnDisabledState.BorderThickness = 1;
            this.btn_buscarCita.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_buscarCita.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_buscarCita.OnDisabledState.IconLeftImage = null;
            this.btn_buscarCita.OnDisabledState.IconRightImage = null;
            this.btn_buscarCita.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarCita.onHoverState.BorderRadius = 39;
            this.btn_buscarCita.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_buscarCita.onHoverState.BorderThickness = 1;
            this.btn_buscarCita.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarCita.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_buscarCita.onHoverState.IconLeftImage = null;
            this.btn_buscarCita.onHoverState.IconRightImage = null;
            this.btn_buscarCita.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarCita.OnIdleState.BorderRadius = 39;
            this.btn_buscarCita.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_buscarCita.OnIdleState.BorderThickness = 1;
            this.btn_buscarCita.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarCita.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_buscarCita.OnIdleState.IconLeftImage = null;
            this.btn_buscarCita.OnIdleState.IconRightImage = null;
            this.btn_buscarCita.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarCita.OnPressedState.BorderRadius = 39;
            this.btn_buscarCita.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_buscarCita.OnPressedState.BorderThickness = 1;
            this.btn_buscarCita.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarCita.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_buscarCita.OnPressedState.IconLeftImage = null;
            this.btn_buscarCita.OnPressedState.IconRightImage = null;
            this.btn_buscarCita.Size = new System.Drawing.Size(91, 39);
            this.btn_buscarCita.TabIndex = 33;
            this.btn_buscarCita.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_buscarCita.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_buscarCita.TextMarginLeft = 0;
            this.btn_buscarCita.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_buscarCita.UseDefaultRadiusAndThickness = true;
            this.btn_buscarCita.Click += new System.EventHandler(this.btn_buscarCita_Click);
            // 
            // btn_registroCita
            // 
            this.btn_registroCita.AllowAnimations = true;
            this.btn_registroCita.AllowMouseEffects = true;
            this.btn_registroCita.AllowToggling = false;
            this.btn_registroCita.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_registroCita.AnimationSpeed = 200;
            this.btn_registroCita.AutoGenerateColors = false;
            this.btn_registroCita.AutoRoundBorders = true;
            this.btn_registroCita.AutoSizeLeftIcon = true;
            this.btn_registroCita.AutoSizeRightIcon = true;
            this.btn_registroCita.BackColor = System.Drawing.Color.Transparent;
            this.btn_registroCita.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_registroCita.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_registroCita.BackgroundImage")));
            this.btn_registroCita.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_registroCita.ButtonText = "Registrar";
            this.btn_registroCita.ButtonTextMarginLeft = 0;
            this.btn_registroCita.ColorContrastOnClick = 45;
            this.btn_registroCita.ColorContrastOnHover = 45;
            this.btn_registroCita.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn_registroCita.CustomizableEdges = borderEdges8;
            this.btn_registroCita.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_registroCita.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_registroCita.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_registroCita.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_registroCita.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btn_registroCita.Font = new System.Drawing.Font("Montserrat", 8F, System.Drawing.FontStyle.Bold);
            this.btn_registroCita.ForeColor = System.Drawing.Color.White;
            this.btn_registroCita.IconLeft = null;
            this.btn_registroCita.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_registroCita.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_registroCita.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_registroCita.IconMarginLeft = 11;
            this.btn_registroCita.IconPadding = 10;
            this.btn_registroCita.IconRight = null;
            this.btn_registroCita.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_registroCita.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_registroCita.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_registroCita.IconSize = 25;
            this.btn_registroCita.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_registroCita.IdleBorderRadius = 0;
            this.btn_registroCita.IdleBorderThickness = 0;
            this.btn_registroCita.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_registroCita.IdleIconLeftImage = null;
            this.btn_registroCita.IdleIconRightImage = null;
            this.btn_registroCita.IndicateFocus = false;
            this.btn_registroCita.Location = new System.Drawing.Point(109, 433);
            this.btn_registroCita.Name = "btn_registroCita";
            this.btn_registroCita.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_registroCita.OnDisabledState.BorderRadius = 39;
            this.btn_registroCita.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_registroCita.OnDisabledState.BorderThickness = 1;
            this.btn_registroCita.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_registroCita.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_registroCita.OnDisabledState.IconLeftImage = null;
            this.btn_registroCita.OnDisabledState.IconRightImage = null;
            this.btn_registroCita.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registroCita.onHoverState.BorderRadius = 39;
            this.btn_registroCita.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_registroCita.onHoverState.BorderThickness = 1;
            this.btn_registroCita.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registroCita.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_registroCita.onHoverState.IconLeftImage = null;
            this.btn_registroCita.onHoverState.IconRightImage = null;
            this.btn_registroCita.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registroCita.OnIdleState.BorderRadius = 39;
            this.btn_registroCita.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_registroCita.OnIdleState.BorderThickness = 1;
            this.btn_registroCita.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registroCita.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_registroCita.OnIdleState.IconLeftImage = null;
            this.btn_registroCita.OnIdleState.IconRightImage = null;
            this.btn_registroCita.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registroCita.OnPressedState.BorderRadius = 39;
            this.btn_registroCita.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_registroCita.OnPressedState.BorderThickness = 1;
            this.btn_registroCita.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registroCita.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_registroCita.OnPressedState.IconLeftImage = null;
            this.btn_registroCita.OnPressedState.IconRightImage = null;
            this.btn_registroCita.Size = new System.Drawing.Size(91, 39);
            this.btn_registroCita.TabIndex = 32;
            this.btn_registroCita.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_registroCita.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_registroCita.TextMarginLeft = 0;
            this.btn_registroCita.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_registroCita.UseDefaultRadiusAndThickness = true;
            this.btn_registroCita.Click += new System.EventHandler(this.btn_registroCita_Click);
            // 
            // dgv_citas
            // 
            this.dgv_citas.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.dgv_citas.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.dgv_citas.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dgv_citas.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgv_citas.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            this.dgv_citas.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgv_citas.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgv_citas.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgv_citas.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dgv_citas.ColumnHeadersHeight = 40;
            this.dgv_citas.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgv_citas.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv_citas.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv_citas.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv_citas.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgv_citas.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgv_citas.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv_citas.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgv_citas.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgv_citas.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgv_citas.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgv_citas.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgv_citas.CurrentTheme.Name = null;
            this.dgv_citas.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgv_citas.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv_citas.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv_citas.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv_citas.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgv_citas.DefaultCellStyle = dataGridViewCellStyle6;
            this.dgv_citas.EnableHeadersVisualStyles = false;
            this.dgv_citas.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv_citas.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgv_citas.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgv_citas.HeaderForeColor = System.Drawing.Color.White;
            this.dgv_citas.Location = new System.Drawing.Point(58, 67);
            this.dgv_citas.Name = "dgv_citas";
            this.dgv_citas.ReadOnly = true;
            this.dgv_citas.RowHeadersVisible = false;
            this.dgv_citas.RowHeadersWidth = 51;
            this.dgv_citas.RowTemplate.Height = 40;
            this.dgv_citas.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv_citas.Size = new System.Drawing.Size(413, 330);
            this.dgv_citas.TabIndex = 31;
            this.dgv_citas.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dgv_citas.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_citas_CellDoubleClick);
            // 
            // txt_telefonoCliente
            // 
            this.txt_telefonoCliente.AcceptsReturn = false;
            this.txt_telefonoCliente.AcceptsTab = false;
            this.txt_telefonoCliente.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txt_telefonoCliente.AnimationSpeed = 200;
            this.txt_telefonoCliente.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_telefonoCliente.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_telefonoCliente.AutoSizeHeight = true;
            this.txt_telefonoCliente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_telefonoCliente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_telefonoCliente.BackgroundImage")));
            this.txt_telefonoCliente.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_telefonoCliente.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_telefonoCliente.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_telefonoCliente.BorderColorIdle = System.Drawing.Color.White;
            this.txt_telefonoCliente.BorderRadius = 1;
            this.txt_telefonoCliente.BorderThickness = 2;
            this.txt_telefonoCliente.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_telefonoCliente.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_telefonoCliente.DefaultFont = new System.Drawing.Font("Montserrat", 11F);
            this.txt_telefonoCliente.DefaultText = "";
            this.txt_telefonoCliente.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_telefonoCliente.ForeColor = System.Drawing.Color.White;
            this.txt_telefonoCliente.HideSelection = true;
            this.txt_telefonoCliente.IconLeft = null;
            this.txt_telefonoCliente.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_telefonoCliente.IconPadding = 10;
            this.txt_telefonoCliente.IconRight = null;
            this.txt_telefonoCliente.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_telefonoCliente.Lines = new string[0];
            this.txt_telefonoCliente.Location = new System.Drawing.Point(11, 270);
            this.txt_telefonoCliente.MaxLength = 15;
            this.txt_telefonoCliente.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_telefonoCliente.Modified = false;
            this.txt_telefonoCliente.Multiline = false;
            this.txt_telefonoCliente.Name = "txt_telefonoCliente";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_telefonoCliente.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.White;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_telefonoCliente.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_telefonoCliente.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.White;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_telefonoCliente.OnIdleState = stateProperties24;
            this.txt_telefonoCliente.Padding = new System.Windows.Forms.Padding(3);
            this.txt_telefonoCliente.PasswordChar = '\0';
            this.txt_telefonoCliente.PlaceholderForeColor = System.Drawing.Color.White;
            this.txt_telefonoCliente.PlaceholderText = "";
            this.txt_telefonoCliente.ReadOnly = false;
            this.txt_telefonoCliente.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_telefonoCliente.SelectedText = "";
            this.txt_telefonoCliente.SelectionLength = 0;
            this.txt_telefonoCliente.SelectionStart = 0;
            this.txt_telefonoCliente.ShortcutsEnabled = true;
            this.txt_telefonoCliente.Size = new System.Drawing.Size(190, 27);
            this.txt_telefonoCliente.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txt_telefonoCliente.TabIndex = 59;
            this.txt_telefonoCliente.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_telefonoCliente.TextMarginBottom = 0;
            this.txt_telefonoCliente.TextMarginLeft = 3;
            this.txt_telefonoCliente.TextMarginTop = 1;
            this.txt_telefonoCliente.TextPlaceholder = "";
            this.txt_telefonoCliente.UseSystemPasswordChar = false;
            this.txt_telefonoCliente.WordWrap = true;
            this.txt_telefonoCliente.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_telefonoCliente_KeyPress);
            // 
            // txt_correoCliente
            // 
            this.txt_correoCliente.AcceptsReturn = false;
            this.txt_correoCliente.AcceptsTab = false;
            this.txt_correoCliente.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txt_correoCliente.AnimationSpeed = 200;
            this.txt_correoCliente.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_correoCliente.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_correoCliente.AutoSizeHeight = true;
            this.txt_correoCliente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_correoCliente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_correoCliente.BackgroundImage")));
            this.txt_correoCliente.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_correoCliente.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_correoCliente.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_correoCliente.BorderColorIdle = System.Drawing.Color.White;
            this.txt_correoCliente.BorderRadius = 1;
            this.txt_correoCliente.BorderThickness = 2;
            this.txt_correoCliente.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_correoCliente.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_correoCliente.DefaultFont = new System.Drawing.Font("Montserrat", 11F);
            this.txt_correoCliente.DefaultText = "";
            this.txt_correoCliente.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_correoCliente.ForeColor = System.Drawing.Color.White;
            this.txt_correoCliente.HideSelection = true;
            this.txt_correoCliente.IconLeft = null;
            this.txt_correoCliente.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_correoCliente.IconPadding = 10;
            this.txt_correoCliente.IconRight = null;
            this.txt_correoCliente.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_correoCliente.Lines = new string[0];
            this.txt_correoCliente.Location = new System.Drawing.Point(11, 205);
            this.txt_correoCliente.MaxLength = 160;
            this.txt_correoCliente.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_correoCliente.Modified = false;
            this.txt_correoCliente.Multiline = false;
            this.txt_correoCliente.Name = "txt_correoCliente";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_correoCliente.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.White;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_correoCliente.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_correoCliente.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.White;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            stateProperties28.ForeColor = System.Drawing.Color.White;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_correoCliente.OnIdleState = stateProperties28;
            this.txt_correoCliente.Padding = new System.Windows.Forms.Padding(3);
            this.txt_correoCliente.PasswordChar = '\0';
            this.txt_correoCliente.PlaceholderForeColor = System.Drawing.Color.White;
            this.txt_correoCliente.PlaceholderText = "";
            this.txt_correoCliente.ReadOnly = false;
            this.txt_correoCliente.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_correoCliente.SelectedText = "";
            this.txt_correoCliente.SelectionLength = 0;
            this.txt_correoCliente.SelectionStart = 0;
            this.txt_correoCliente.ShortcutsEnabled = true;
            this.txt_correoCliente.Size = new System.Drawing.Size(190, 27);
            this.txt_correoCliente.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txt_correoCliente.TabIndex = 58;
            this.txt_correoCliente.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_correoCliente.TextMarginBottom = 0;
            this.txt_correoCliente.TextMarginLeft = 3;
            this.txt_correoCliente.TextMarginTop = 1;
            this.txt_correoCliente.TextPlaceholder = "";
            this.txt_correoCliente.UseSystemPasswordChar = false;
            this.txt_correoCliente.WordWrap = true;
            // 
            // txt_nombreCliente
            // 
            this.txt_nombreCliente.AcceptsReturn = false;
            this.txt_nombreCliente.AcceptsTab = false;
            this.txt_nombreCliente.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txt_nombreCliente.AnimationSpeed = 200;
            this.txt_nombreCliente.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_nombreCliente.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_nombreCliente.AutoSizeHeight = true;
            this.txt_nombreCliente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_nombreCliente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_nombreCliente.BackgroundImage")));
            this.txt_nombreCliente.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_nombreCliente.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_nombreCliente.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_nombreCliente.BorderColorIdle = System.Drawing.Color.White;
            this.txt_nombreCliente.BorderRadius = 1;
            this.txt_nombreCliente.BorderThickness = 2;
            this.txt_nombreCliente.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_nombreCliente.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_nombreCliente.DefaultFont = new System.Drawing.Font("Montserrat", 11F);
            this.txt_nombreCliente.DefaultText = "";
            this.txt_nombreCliente.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_nombreCliente.ForeColor = System.Drawing.Color.White;
            this.txt_nombreCliente.HideSelection = true;
            this.txt_nombreCliente.IconLeft = null;
            this.txt_nombreCliente.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_nombreCliente.IconPadding = 10;
            this.txt_nombreCliente.IconRight = null;
            this.txt_nombreCliente.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_nombreCliente.Lines = new string[0];
            this.txt_nombreCliente.Location = new System.Drawing.Point(11, 140);
            this.txt_nombreCliente.MaxLength = 100;
            this.txt_nombreCliente.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_nombreCliente.Modified = false;
            this.txt_nombreCliente.Multiline = false;
            this.txt_nombreCliente.Name = "txt_nombreCliente";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_nombreCliente.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.White;
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_nombreCliente.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_nombreCliente.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.White;
            stateProperties32.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            stateProperties32.ForeColor = System.Drawing.Color.White;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_nombreCliente.OnIdleState = stateProperties32;
            this.txt_nombreCliente.Padding = new System.Windows.Forms.Padding(3);
            this.txt_nombreCliente.PasswordChar = '\0';
            this.txt_nombreCliente.PlaceholderForeColor = System.Drawing.Color.White;
            this.txt_nombreCliente.PlaceholderText = "";
            this.txt_nombreCliente.ReadOnly = false;
            this.txt_nombreCliente.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_nombreCliente.SelectedText = "";
            this.txt_nombreCliente.SelectionLength = 0;
            this.txt_nombreCliente.SelectionStart = 0;
            this.txt_nombreCliente.ShortcutsEnabled = true;
            this.txt_nombreCliente.Size = new System.Drawing.Size(190, 27);
            this.txt_nombreCliente.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txt_nombreCliente.TabIndex = 57;
            this.txt_nombreCliente.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_nombreCliente.TextMarginBottom = 0;
            this.txt_nombreCliente.TextMarginLeft = 3;
            this.txt_nombreCliente.TextMarginTop = 1;
            this.txt_nombreCliente.TextPlaceholder = "";
            this.txt_nombreCliente.UseSystemPasswordChar = false;
            this.txt_nombreCliente.WordWrap = true;
            this.txt_nombreCliente.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_nombreCliente_KeyPress);
            // 
            // txt_identCliente
            // 
            this.txt_identCliente.AcceptsReturn = false;
            this.txt_identCliente.AcceptsTab = false;
            this.txt_identCliente.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txt_identCliente.AnimationSpeed = 200;
            this.txt_identCliente.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_identCliente.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_identCliente.AutoSizeHeight = true;
            this.txt_identCliente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_identCliente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_identCliente.BackgroundImage")));
            this.txt_identCliente.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_identCliente.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_identCliente.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_identCliente.BorderColorIdle = System.Drawing.Color.White;
            this.txt_identCliente.BorderRadius = 1;
            this.txt_identCliente.BorderThickness = 2;
            this.txt_identCliente.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_identCliente.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_identCliente.DefaultFont = new System.Drawing.Font("Montserrat", 11F);
            this.txt_identCliente.DefaultText = "";
            this.txt_identCliente.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_identCliente.ForeColor = System.Drawing.Color.White;
            this.txt_identCliente.HideSelection = true;
            this.txt_identCliente.IconLeft = null;
            this.txt_identCliente.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_identCliente.IconPadding = 10;
            this.txt_identCliente.IconRight = null;
            this.txt_identCliente.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_identCliente.Lines = new string[0];
            this.txt_identCliente.Location = new System.Drawing.Point(11, 72);
            this.txt_identCliente.MaxLength = 20;
            this.txt_identCliente.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_identCliente.Modified = false;
            this.txt_identCliente.Multiline = false;
            this.txt_identCliente.Name = "txt_identCliente";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_identCliente.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.White;
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_identCliente.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_identCliente.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.White;
            stateProperties36.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            stateProperties36.ForeColor = System.Drawing.Color.White;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_identCliente.OnIdleState = stateProperties36;
            this.txt_identCliente.Padding = new System.Windows.Forms.Padding(3);
            this.txt_identCliente.PasswordChar = '\0';
            this.txt_identCliente.PlaceholderForeColor = System.Drawing.Color.White;
            this.txt_identCliente.PlaceholderText = "";
            this.txt_identCliente.ReadOnly = false;
            this.txt_identCliente.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_identCliente.SelectedText = "";
            this.txt_identCliente.SelectionLength = 0;
            this.txt_identCliente.SelectionStart = 0;
            this.txt_identCliente.ShortcutsEnabled = true;
            this.txt_identCliente.Size = new System.Drawing.Size(190, 27);
            this.txt_identCliente.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txt_identCliente.TabIndex = 56;
            this.txt_identCliente.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_identCliente.TextMarginBottom = 0;
            this.txt_identCliente.TextMarginLeft = 3;
            this.txt_identCliente.TextMarginTop = 1;
            this.txt_identCliente.TextPlaceholder = "";
            this.txt_identCliente.UseSystemPasswordChar = false;
            this.txt_identCliente.WordWrap = true;
            this.txt_identCliente.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_identCliente_KeyPress);
            // 
            // label4
            // 
            this.label4.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(27)))), ((int)(((byte)(42)))));
            this.label4.Location = new System.Drawing.Point(11, 244);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(68, 20);
            this.label4.TabIndex = 55;
            this.label4.Text = "Teléfono";
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(27)))), ((int)(((byte)(42)))));
            this.label3.Location = new System.Drawing.Point(11, 178);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(57, 20);
            this.label3.TabIndex = 54;
            this.label3.Text = "Correo";
            // 
            // label2
            // 
            this.label2.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(27)))), ((int)(((byte)(42)))));
            this.label2.Location = new System.Drawing.Point(11, 46);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(105, 20);
            this.label2.TabIndex = 53;
            this.label2.Text = "Identificación";
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(27)))), ((int)(((byte)(42)))));
            this.label1.Location = new System.Drawing.Point(11, 112);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(67, 20);
            this.label1.TabIndex = 52;
            this.label1.Text = "Nombre";
            // 
            // label5
            // 
            this.label5.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(27)))), ((int)(((byte)(42)))));
            this.label5.Location = new System.Drawing.Point(11, 309);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(59, 20);
            this.label5.TabIndex = 60;
            this.label5.Text = "Doctor";
            // 
            // cmb_Doctor
            // 
            this.cmb_Doctor.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.cmb_Doctor.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.cmb_Doctor.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmb_Doctor.Font = new System.Drawing.Font("Montserrat", 9F);
            this.cmb_Doctor.ForeColor = System.Drawing.Color.White;
            this.cmb_Doctor.FormattingEnabled = true;
            this.cmb_Doctor.Location = new System.Drawing.Point(11, 341);
            this.cmb_Doctor.MaxLength = 100;
            this.cmb_Doctor.Name = "cmb_Doctor";
            this.cmb_Doctor.Size = new System.Drawing.Size(182, 24);
            this.cmb_Doctor.TabIndex = 61;
            // 
            // dtp_fechaCita
            // 
            this.dtp_fechaCita.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.dtp_fechaCita.BackColor = System.Drawing.Color.Transparent;
            this.dtp_fechaCita.BorderColor = System.Drawing.Color.Transparent;
            this.dtp_fechaCita.BorderRadius = 0;
            this.dtp_fechaCita.CalendarFont = new System.Drawing.Font("Montserrat", 11F);
            this.dtp_fechaCita.CalendarForeColor = System.Drawing.Color.White;
            this.dtp_fechaCita.CalendarMonthBackground = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.dtp_fechaCita.Color = System.Drawing.Color.Transparent;
            this.dtp_fechaCita.CustomFormat = "MM/dd/yyyy";
            this.dtp_fechaCita.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtp_fechaCita.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtp_fechaCita.DisabledColor = System.Drawing.Color.Gray;
            this.dtp_fechaCita.DisplayWeekNumbers = false;
            this.dtp_fechaCita.DPHeight = 0;
            this.dtp_fechaCita.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtp_fechaCita.FillDatePicker = false;
            this.dtp_fechaCita.Font = new System.Drawing.Font("Montserrat", 10F);
            this.dtp_fechaCita.ForeColor = System.Drawing.Color.White;
            this.dtp_fechaCita.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtp_fechaCita.Icon = ((System.Drawing.Image)(resources.GetObject("dtp_fechaCita.Icon")));
            this.dtp_fechaCita.IconColor = System.Drawing.Color.White;
            this.dtp_fechaCita.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtp_fechaCita.LeftTextMargin = 5;
            this.dtp_fechaCita.Location = new System.Drawing.Point(11, 494);
            this.dtp_fechaCita.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtp_fechaCita.Name = "dtp_fechaCita";
            this.dtp_fechaCita.Size = new System.Drawing.Size(118, 32);
            this.dtp_fechaCita.TabIndex = 63;
            this.dtp_fechaCita.Value = new System.DateTime(2021, 11, 26, 0, 0, 0, 0);
            // 
            // dtp_horaCita
            // 
            this.dtp_horaCita.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.dtp_horaCita.CalendarFont = new System.Drawing.Font("Montserrat", 9F);
            this.dtp_horaCita.CustomFormat = "HH:mm";
            this.dtp_horaCita.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtp_horaCita.Location = new System.Drawing.Point(149, 501);
            this.dtp_horaCita.Name = "dtp_horaCita";
            this.dtp_horaCita.ShowUpDown = true;
            this.dtp_horaCita.Size = new System.Drawing.Size(93, 20);
            this.dtp_horaCita.TabIndex = 64;
            this.dtp_horaCita.Value = new System.DateTime(2021, 11, 26, 0, 0, 0, 0);
            // 
            // CitasElipse
            // 
            this.CitasElipse.ElipseRadius = 7;
            this.CitasElipse.TargetControl = this.dgv_citas;
            // 
            // txt_descCita
            // 
            this.txt_descCita.AcceptsReturn = false;
            this.txt_descCita.AcceptsTab = false;
            this.txt_descCita.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txt_descCita.AnimationSpeed = 200;
            this.txt_descCita.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_descCita.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_descCita.AutoSizeHeight = true;
            this.txt_descCita.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_descCita.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_descCita.BackgroundImage")));
            this.txt_descCita.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_descCita.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_descCita.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_descCita.BorderColorIdle = System.Drawing.Color.White;
            this.txt_descCita.BorderRadius = 7;
            this.txt_descCita.BorderThickness = 1;
            this.txt_descCita.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_descCita.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_descCita.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_descCita.DefaultText = "";
            this.txt_descCita.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_descCita.HideSelection = true;
            this.txt_descCita.IconLeft = null;
            this.txt_descCita.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_descCita.IconPadding = 10;
            this.txt_descCita.IconRight = null;
            this.txt_descCita.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_descCita.Lines = new string[0];
            this.txt_descCita.Location = new System.Drawing.Point(11, 413);
            this.txt_descCita.MaxLength = 200;
            this.txt_descCita.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_descCita.Modified = false;
            this.txt_descCita.Multiline = true;
            this.txt_descCita.Name = "txt_descCita";
            stateProperties37.BorderColor = System.Drawing.Color.White;
            stateProperties37.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            stateProperties37.ForeColor = System.Drawing.Color.White;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_descCita.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_descCita.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.White;
            stateProperties39.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_descCita.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.White;
            stateProperties40.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_descCita.OnIdleState = stateProperties40;
            this.txt_descCita.Padding = new System.Windows.Forms.Padding(3);
            this.txt_descCita.PasswordChar = '\0';
            this.txt_descCita.PlaceholderForeColor = System.Drawing.Color.White;
            this.txt_descCita.PlaceholderText = "";
            this.txt_descCita.ReadOnly = false;
            this.txt_descCita.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_descCita.SelectedText = "";
            this.txt_descCita.SelectionLength = 0;
            this.txt_descCita.SelectionStart = 0;
            this.txt_descCita.ShortcutsEnabled = true;
            this.txt_descCita.Size = new System.Drawing.Size(260, 60);
            this.txt_descCita.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_descCita.TabIndex = 65;
            this.txt_descCita.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_descCita.TextMarginBottom = 0;
            this.txt_descCita.TextMarginLeft = 3;
            this.txt_descCita.TextMarginTop = 1;
            this.txt_descCita.TextPlaceholder = "";
            this.txt_descCita.UseSystemPasswordChar = false;
            this.txt_descCita.WordWrap = true;
            // 
            // lbl_descCitas
            // 
            this.lbl_descCitas.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lbl_descCitas.AutoSize = true;
            this.lbl_descCitas.Font = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_descCitas.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(27)))), ((int)(((byte)(42)))));
            this.lbl_descCitas.Location = new System.Drawing.Point(11, 381);
            this.lbl_descCitas.Name = "lbl_descCitas";
            this.lbl_descCitas.Size = new System.Drawing.Size(93, 20);
            this.lbl_descCitas.TabIndex = 66;
            this.lbl_descCitas.Text = "Descripción";
            // 
            // TimeElipse
            // 
            this.TimeElipse.ElipseRadius = 7;
            this.TimeElipse.TargetControl = this.dtp_horaCita;
            // 
            // FormCitas
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.ClientSize = new System.Drawing.Size(800, 541);
            this.Controls.Add(this.lbl_descCitas);
            this.Controls.Add(this.txt_descCita);
            this.Controls.Add(this.dtp_horaCita);
            this.Controls.Add(this.dtp_fechaCita);
            this.Controls.Add(this.cmb_Doctor);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.txt_telefonoCliente);
            this.Controls.Add(this.txt_correoCliente);
            this.Controls.Add(this.txt_nombreCliente);
            this.Controls.Add(this.txt_identCliente);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormCitas";
            this.Text = "Citas";
            this.Load += new System.EventHandler(this.FormCitas_Load);
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgv_citas)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_eliminarCita;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_modificarCita;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_buscarCita;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_registroCita;
        private Bunifu.UI.WinForms.BunifuDataGridView dgv_citas;
        private Bunifu.UI.WinForms.BunifuTextBox txt_telefonoCliente;
        private Bunifu.UI.WinForms.BunifuTextBox txt_correoCliente;
        private Bunifu.UI.WinForms.BunifuTextBox txt_nombreCliente;
        private Bunifu.UI.WinForms.BunifuTextBox txt_identCliente;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.ComboBox cmb_Doctor;
        private Bunifu.UI.WinForms.BunifuDatePicker dtp_fechaCita;
        private System.Windows.Forms.DateTimePicker dtp_horaCita;
        private Bunifu.Framework.UI.BunifuElipse CitasElipse;
        private Bunifu.UI.WinForms.BunifuTextBox txt_descCita;
        private System.Windows.Forms.Label lbl_descCitas;
        private Bunifu.Framework.UI.BunifuElipse TimeElipse;
    }
}