
namespace CapaPresentacion.Forms
{
    partial class FormCitas
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormCitas));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btn_eliminarDoctor = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_modificarDoctor = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_buscarDoctor = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_registro = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dgv_doctores = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.txt_telefonoCliente = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_correoCliente = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_nombreCliente = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_identCliente = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.cmb_Doctor = new System.Windows.Forms.ComboBox();
            this.dtp_fechaCita = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.dtp_horaCita = new System.Windows.Forms.DateTimePicker();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_doctores)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panel1.Controls.Add(this.btn_eliminarDoctor);
            this.panel1.Controls.Add(this.btn_modificarDoctor);
            this.panel1.Controls.Add(this.btn_buscarDoctor);
            this.panel1.Controls.Add(this.btn_registro);
            this.panel1.Controls.Add(this.dgv_doctores);
            this.panel1.Location = new System.Drawing.Point(365, 1);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(437, 494);
            this.panel1.TabIndex = 26;
            // 
            // btn_eliminarDoctor
            // 
            this.btn_eliminarDoctor.AllowAnimations = true;
            this.btn_eliminarDoctor.AllowMouseEffects = true;
            this.btn_eliminarDoctor.AllowToggling = false;
            this.btn_eliminarDoctor.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_eliminarDoctor.AnimationSpeed = 200;
            this.btn_eliminarDoctor.AutoGenerateColors = false;
            this.btn_eliminarDoctor.AutoRoundBorders = true;
            this.btn_eliminarDoctor.AutoSizeLeftIcon = true;
            this.btn_eliminarDoctor.AutoSizeRightIcon = true;
            this.btn_eliminarDoctor.BackColor = System.Drawing.Color.Transparent;
            this.btn_eliminarDoctor.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_eliminarDoctor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_eliminarDoctor.BackgroundImage")));
            this.btn_eliminarDoctor.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminarDoctor.ButtonText = "Eliminar";
            this.btn_eliminarDoctor.ButtonTextMarginLeft = 0;
            this.btn_eliminarDoctor.ColorContrastOnClick = 45;
            this.btn_eliminarDoctor.ColorContrastOnHover = 45;
            this.btn_eliminarDoctor.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_eliminarDoctor.CustomizableEdges = borderEdges5;
            this.btn_eliminarDoctor.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_eliminarDoctor.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_eliminarDoctor.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_eliminarDoctor.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_eliminarDoctor.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btn_eliminarDoctor.Font = new System.Drawing.Font("Montserrat", 8F, System.Drawing.FontStyle.Bold);
            this.btn_eliminarDoctor.ForeColor = System.Drawing.Color.White;
            this.btn_eliminarDoctor.IconLeft = null;
            this.btn_eliminarDoctor.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_eliminarDoctor.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_eliminarDoctor.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_eliminarDoctor.IconMarginLeft = 11;
            this.btn_eliminarDoctor.IconPadding = 10;
            this.btn_eliminarDoctor.IconRight = null;
            this.btn_eliminarDoctor.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_eliminarDoctor.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_eliminarDoctor.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_eliminarDoctor.IconSize = 25;
            this.btn_eliminarDoctor.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_eliminarDoctor.IdleBorderRadius = 0;
            this.btn_eliminarDoctor.IdleBorderThickness = 0;
            this.btn_eliminarDoctor.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_eliminarDoctor.IdleIconLeftImage = null;
            this.btn_eliminarDoctor.IdleIconRightImage = null;
            this.btn_eliminarDoctor.IndicateFocus = false;
            this.btn_eliminarDoctor.Location = new System.Drawing.Point(312, 387);
            this.btn_eliminarDoctor.Name = "btn_eliminarDoctor";
            this.btn_eliminarDoctor.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_eliminarDoctor.OnDisabledState.BorderRadius = 39;
            this.btn_eliminarDoctor.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminarDoctor.OnDisabledState.BorderThickness = 1;
            this.btn_eliminarDoctor.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_eliminarDoctor.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_eliminarDoctor.OnDisabledState.IconLeftImage = null;
            this.btn_eliminarDoctor.OnDisabledState.IconRightImage = null;
            this.btn_eliminarDoctor.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarDoctor.onHoverState.BorderRadius = 39;
            this.btn_eliminarDoctor.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminarDoctor.onHoverState.BorderThickness = 1;
            this.btn_eliminarDoctor.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarDoctor.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminarDoctor.onHoverState.IconLeftImage = null;
            this.btn_eliminarDoctor.onHoverState.IconRightImage = null;
            this.btn_eliminarDoctor.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarDoctor.OnIdleState.BorderRadius = 39;
            this.btn_eliminarDoctor.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminarDoctor.OnIdleState.BorderThickness = 1;
            this.btn_eliminarDoctor.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarDoctor.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminarDoctor.OnIdleState.IconLeftImage = null;
            this.btn_eliminarDoctor.OnIdleState.IconRightImage = null;
            this.btn_eliminarDoctor.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarDoctor.OnPressedState.BorderRadius = 39;
            this.btn_eliminarDoctor.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminarDoctor.OnPressedState.BorderThickness = 1;
            this.btn_eliminarDoctor.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminarDoctor.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminarDoctor.OnPressedState.IconLeftImage = null;
            this.btn_eliminarDoctor.OnPressedState.IconRightImage = null;
            this.btn_eliminarDoctor.Size = new System.Drawing.Size(91, 39);
            this.btn_eliminarDoctor.TabIndex = 35;
            this.btn_eliminarDoctor.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_eliminarDoctor.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_eliminarDoctor.TextMarginLeft = 0;
            this.btn_eliminarDoctor.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_eliminarDoctor.UseDefaultRadiusAndThickness = true;
            // 
            // btn_modificarDoctor
            // 
            this.btn_modificarDoctor.AllowAnimations = true;
            this.btn_modificarDoctor.AllowMouseEffects = true;
            this.btn_modificarDoctor.AllowToggling = false;
            this.btn_modificarDoctor.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_modificarDoctor.AnimationSpeed = 200;
            this.btn_modificarDoctor.AutoGenerateColors = false;
            this.btn_modificarDoctor.AutoRoundBorders = true;
            this.btn_modificarDoctor.AutoSizeLeftIcon = true;
            this.btn_modificarDoctor.AutoSizeRightIcon = true;
            this.btn_modificarDoctor.BackColor = System.Drawing.Color.Transparent;
            this.btn_modificarDoctor.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_modificarDoctor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_modificarDoctor.BackgroundImage")));
            this.btn_modificarDoctor.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_modificarDoctor.ButtonText = "Modificar";
            this.btn_modificarDoctor.ButtonTextMarginLeft = 0;
            this.btn_modificarDoctor.ColorContrastOnClick = 45;
            this.btn_modificarDoctor.ColorContrastOnHover = 45;
            this.btn_modificarDoctor.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btn_modificarDoctor.CustomizableEdges = borderEdges6;
            this.btn_modificarDoctor.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_modificarDoctor.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_modificarDoctor.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_modificarDoctor.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_modificarDoctor.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btn_modificarDoctor.Font = new System.Drawing.Font("Montserrat", 8F, System.Drawing.FontStyle.Bold);
            this.btn_modificarDoctor.ForeColor = System.Drawing.Color.White;
            this.btn_modificarDoctor.IconLeft = null;
            this.btn_modificarDoctor.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_modificarDoctor.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_modificarDoctor.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_modificarDoctor.IconMarginLeft = 11;
            this.btn_modificarDoctor.IconPadding = 10;
            this.btn_modificarDoctor.IconRight = null;
            this.btn_modificarDoctor.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_modificarDoctor.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_modificarDoctor.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_modificarDoctor.IconSize = 25;
            this.btn_modificarDoctor.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_modificarDoctor.IdleBorderRadius = 0;
            this.btn_modificarDoctor.IdleBorderThickness = 0;
            this.btn_modificarDoctor.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_modificarDoctor.IdleIconLeftImage = null;
            this.btn_modificarDoctor.IdleIconRightImage = null;
            this.btn_modificarDoctor.IndicateFocus = false;
            this.btn_modificarDoctor.Location = new System.Drawing.Point(215, 387);
            this.btn_modificarDoctor.Name = "btn_modificarDoctor";
            this.btn_modificarDoctor.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_modificarDoctor.OnDisabledState.BorderRadius = 39;
            this.btn_modificarDoctor.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_modificarDoctor.OnDisabledState.BorderThickness = 1;
            this.btn_modificarDoctor.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_modificarDoctor.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_modificarDoctor.OnDisabledState.IconLeftImage = null;
            this.btn_modificarDoctor.OnDisabledState.IconRightImage = null;
            this.btn_modificarDoctor.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarDoctor.onHoverState.BorderRadius = 39;
            this.btn_modificarDoctor.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_modificarDoctor.onHoverState.BorderThickness = 1;
            this.btn_modificarDoctor.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarDoctor.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_modificarDoctor.onHoverState.IconLeftImage = null;
            this.btn_modificarDoctor.onHoverState.IconRightImage = null;
            this.btn_modificarDoctor.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarDoctor.OnIdleState.BorderRadius = 39;
            this.btn_modificarDoctor.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_modificarDoctor.OnIdleState.BorderThickness = 1;
            this.btn_modificarDoctor.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarDoctor.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_modificarDoctor.OnIdleState.IconLeftImage = null;
            this.btn_modificarDoctor.OnIdleState.IconRightImage = null;
            this.btn_modificarDoctor.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarDoctor.OnPressedState.BorderRadius = 39;
            this.btn_modificarDoctor.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_modificarDoctor.OnPressedState.BorderThickness = 1;
            this.btn_modificarDoctor.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_modificarDoctor.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_modificarDoctor.OnPressedState.IconLeftImage = null;
            this.btn_modificarDoctor.OnPressedState.IconRightImage = null;
            this.btn_modificarDoctor.Size = new System.Drawing.Size(91, 39);
            this.btn_modificarDoctor.TabIndex = 34;
            this.btn_modificarDoctor.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_modificarDoctor.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_modificarDoctor.TextMarginLeft = 0;
            this.btn_modificarDoctor.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_modificarDoctor.UseDefaultRadiusAndThickness = true;
            // 
            // btn_buscarDoctor
            // 
            this.btn_buscarDoctor.AllowAnimations = true;
            this.btn_buscarDoctor.AllowMouseEffects = true;
            this.btn_buscarDoctor.AllowToggling = false;
            this.btn_buscarDoctor.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_buscarDoctor.AnimationSpeed = 200;
            this.btn_buscarDoctor.AutoGenerateColors = false;
            this.btn_buscarDoctor.AutoRoundBorders = true;
            this.btn_buscarDoctor.AutoSizeLeftIcon = true;
            this.btn_buscarDoctor.AutoSizeRightIcon = true;
            this.btn_buscarDoctor.BackColor = System.Drawing.Color.Transparent;
            this.btn_buscarDoctor.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_buscarDoctor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_buscarDoctor.BackgroundImage")));
            this.btn_buscarDoctor.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_buscarDoctor.ButtonText = "Buscar";
            this.btn_buscarDoctor.ButtonTextMarginLeft = 0;
            this.btn_buscarDoctor.ColorContrastOnClick = 45;
            this.btn_buscarDoctor.ColorContrastOnHover = 45;
            this.btn_buscarDoctor.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn_buscarDoctor.CustomizableEdges = borderEdges7;
            this.btn_buscarDoctor.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_buscarDoctor.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_buscarDoctor.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_buscarDoctor.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_buscarDoctor.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btn_buscarDoctor.Font = new System.Drawing.Font("Montserrat", 8F, System.Drawing.FontStyle.Bold);
            this.btn_buscarDoctor.ForeColor = System.Drawing.Color.White;
            this.btn_buscarDoctor.IconLeft = null;
            this.btn_buscarDoctor.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_buscarDoctor.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_buscarDoctor.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_buscarDoctor.IconMarginLeft = 11;
            this.btn_buscarDoctor.IconPadding = 10;
            this.btn_buscarDoctor.IconRight = null;
            this.btn_buscarDoctor.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_buscarDoctor.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_buscarDoctor.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_buscarDoctor.IconSize = 25;
            this.btn_buscarDoctor.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_buscarDoctor.IdleBorderRadius = 0;
            this.btn_buscarDoctor.IdleBorderThickness = 0;
            this.btn_buscarDoctor.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_buscarDoctor.IdleIconLeftImage = null;
            this.btn_buscarDoctor.IdleIconRightImage = null;
            this.btn_buscarDoctor.IndicateFocus = false;
            this.btn_buscarDoctor.Location = new System.Drawing.Point(118, 387);
            this.btn_buscarDoctor.Name = "btn_buscarDoctor";
            this.btn_buscarDoctor.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_buscarDoctor.OnDisabledState.BorderRadius = 39;
            this.btn_buscarDoctor.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_buscarDoctor.OnDisabledState.BorderThickness = 1;
            this.btn_buscarDoctor.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_buscarDoctor.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_buscarDoctor.OnDisabledState.IconLeftImage = null;
            this.btn_buscarDoctor.OnDisabledState.IconRightImage = null;
            this.btn_buscarDoctor.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarDoctor.onHoverState.BorderRadius = 39;
            this.btn_buscarDoctor.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_buscarDoctor.onHoverState.BorderThickness = 1;
            this.btn_buscarDoctor.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarDoctor.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_buscarDoctor.onHoverState.IconLeftImage = null;
            this.btn_buscarDoctor.onHoverState.IconRightImage = null;
            this.btn_buscarDoctor.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarDoctor.OnIdleState.BorderRadius = 39;
            this.btn_buscarDoctor.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_buscarDoctor.OnIdleState.BorderThickness = 1;
            this.btn_buscarDoctor.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarDoctor.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_buscarDoctor.OnIdleState.IconLeftImage = null;
            this.btn_buscarDoctor.OnIdleState.IconRightImage = null;
            this.btn_buscarDoctor.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarDoctor.OnPressedState.BorderRadius = 39;
            this.btn_buscarDoctor.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_buscarDoctor.OnPressedState.BorderThickness = 1;
            this.btn_buscarDoctor.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_buscarDoctor.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_buscarDoctor.OnPressedState.IconLeftImage = null;
            this.btn_buscarDoctor.OnPressedState.IconRightImage = null;
            this.btn_buscarDoctor.Size = new System.Drawing.Size(91, 39);
            this.btn_buscarDoctor.TabIndex = 33;
            this.btn_buscarDoctor.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_buscarDoctor.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_buscarDoctor.TextMarginLeft = 0;
            this.btn_buscarDoctor.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_buscarDoctor.UseDefaultRadiusAndThickness = true;
            // 
            // btn_registro
            // 
            this.btn_registro.AllowAnimations = true;
            this.btn_registro.AllowMouseEffects = true;
            this.btn_registro.AllowToggling = false;
            this.btn_registro.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_registro.AnimationSpeed = 200;
            this.btn_registro.AutoGenerateColors = false;
            this.btn_registro.AutoRoundBorders = true;
            this.btn_registro.AutoSizeLeftIcon = true;
            this.btn_registro.AutoSizeRightIcon = true;
            this.btn_registro.BackColor = System.Drawing.Color.Transparent;
            this.btn_registro.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_registro.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_registro.BackgroundImage")));
            this.btn_registro.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_registro.ButtonText = "Registrar";
            this.btn_registro.ButtonTextMarginLeft = 0;
            this.btn_registro.ColorContrastOnClick = 45;
            this.btn_registro.ColorContrastOnHover = 45;
            this.btn_registro.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn_registro.CustomizableEdges = borderEdges8;
            this.btn_registro.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_registro.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_registro.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_registro.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_registro.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btn_registro.Font = new System.Drawing.Font("Montserrat", 8F, System.Drawing.FontStyle.Bold);
            this.btn_registro.ForeColor = System.Drawing.Color.White;
            this.btn_registro.IconLeft = null;
            this.btn_registro.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_registro.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_registro.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_registro.IconMarginLeft = 11;
            this.btn_registro.IconPadding = 10;
            this.btn_registro.IconRight = null;
            this.btn_registro.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_registro.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_registro.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_registro.IconSize = 25;
            this.btn_registro.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_registro.IdleBorderRadius = 0;
            this.btn_registro.IdleBorderThickness = 0;
            this.btn_registro.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_registro.IdleIconLeftImage = null;
            this.btn_registro.IdleIconRightImage = null;
            this.btn_registro.IndicateFocus = false;
            this.btn_registro.Location = new System.Drawing.Point(21, 387);
            this.btn_registro.Name = "btn_registro";
            this.btn_registro.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_registro.OnDisabledState.BorderRadius = 39;
            this.btn_registro.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_registro.OnDisabledState.BorderThickness = 1;
            this.btn_registro.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_registro.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_registro.OnDisabledState.IconLeftImage = null;
            this.btn_registro.OnDisabledState.IconRightImage = null;
            this.btn_registro.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registro.onHoverState.BorderRadius = 39;
            this.btn_registro.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_registro.onHoverState.BorderThickness = 1;
            this.btn_registro.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registro.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_registro.onHoverState.IconLeftImage = null;
            this.btn_registro.onHoverState.IconRightImage = null;
            this.btn_registro.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registro.OnIdleState.BorderRadius = 39;
            this.btn_registro.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_registro.OnIdleState.BorderThickness = 1;
            this.btn_registro.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registro.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_registro.OnIdleState.IconLeftImage = null;
            this.btn_registro.OnIdleState.IconRightImage = null;
            this.btn_registro.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registro.OnPressedState.BorderRadius = 39;
            this.btn_registro.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_registro.OnPressedState.BorderThickness = 1;
            this.btn_registro.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_registro.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_registro.OnPressedState.IconLeftImage = null;
            this.btn_registro.OnPressedState.IconRightImage = null;
            this.btn_registro.Size = new System.Drawing.Size(91, 39);
            this.btn_registro.TabIndex = 32;
            this.btn_registro.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_registro.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_registro.TextMarginLeft = 0;
            this.btn_registro.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_registro.UseDefaultRadiusAndThickness = true;
            // 
            // dgv_doctores
            // 
            this.dgv_doctores.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.dgv_doctores.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.dgv_doctores.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dgv_doctores.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgv_doctores.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            this.dgv_doctores.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgv_doctores.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgv_doctores.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgv_doctores.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dgv_doctores.ColumnHeadersHeight = 40;
            this.dgv_doctores.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgv_doctores.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv_doctores.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv_doctores.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv_doctores.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgv_doctores.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgv_doctores.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv_doctores.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgv_doctores.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgv_doctores.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgv_doctores.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgv_doctores.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgv_doctores.CurrentTheme.Name = null;
            this.dgv_doctores.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgv_doctores.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv_doctores.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv_doctores.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv_doctores.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgv_doctores.DefaultCellStyle = dataGridViewCellStyle6;
            this.dgv_doctores.EnableHeadersVisualStyles = false;
            this.dgv_doctores.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv_doctores.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgv_doctores.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgv_doctores.HeaderForeColor = System.Drawing.Color.White;
            this.dgv_doctores.Location = new System.Drawing.Point(58, 67);
            this.dgv_doctores.Name = "dgv_doctores";
            this.dgv_doctores.RowHeadersVisible = false;
            this.dgv_doctores.RowTemplate.Height = 40;
            this.dgv_doctores.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv_doctores.Size = new System.Drawing.Size(325, 284);
            this.dgv_doctores.TabIndex = 31;
            this.dgv_doctores.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // txt_telefonoCliente
            // 
            this.txt_telefonoCliente.AcceptsReturn = false;
            this.txt_telefonoCliente.AcceptsTab = false;
            this.txt_telefonoCliente.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txt_telefonoCliente.AnimationSpeed = 200;
            this.txt_telefonoCliente.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_telefonoCliente.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_telefonoCliente.AutoSizeHeight = true;
            this.txt_telefonoCliente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_telefonoCliente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_telefonoCliente.BackgroundImage")));
            this.txt_telefonoCliente.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_telefonoCliente.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_telefonoCliente.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_telefonoCliente.BorderColorIdle = System.Drawing.Color.White;
            this.txt_telefonoCliente.BorderRadius = 1;
            this.txt_telefonoCliente.BorderThickness = 2;
            this.txt_telefonoCliente.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_telefonoCliente.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_telefonoCliente.DefaultFont = new System.Drawing.Font("Montserrat", 11F);
            this.txt_telefonoCliente.DefaultText = "";
            this.txt_telefonoCliente.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_telefonoCliente.ForeColor = System.Drawing.Color.White;
            this.txt_telefonoCliente.HideSelection = true;
            this.txt_telefonoCliente.IconLeft = null;
            this.txt_telefonoCliente.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_telefonoCliente.IconPadding = 10;
            this.txt_telefonoCliente.IconRight = null;
            this.txt_telefonoCliente.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_telefonoCliente.Lines = new string[0];
            this.txt_telefonoCliente.Location = new System.Drawing.Point(11, 288);
            this.txt_telefonoCliente.MaxLength = 20;
            this.txt_telefonoCliente.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_telefonoCliente.Modified = false;
            this.txt_telefonoCliente.Multiline = false;
            this.txt_telefonoCliente.Name = "txt_telefonoCliente";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_telefonoCliente.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.White;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_telefonoCliente.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_telefonoCliente.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.White;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_telefonoCliente.OnIdleState = stateProperties20;
            this.txt_telefonoCliente.Padding = new System.Windows.Forms.Padding(3);
            this.txt_telefonoCliente.PasswordChar = '\0';
            this.txt_telefonoCliente.PlaceholderForeColor = System.Drawing.Color.White;
            this.txt_telefonoCliente.PlaceholderText = "";
            this.txt_telefonoCliente.ReadOnly = false;
            this.txt_telefonoCliente.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_telefonoCliente.SelectedText = "";
            this.txt_telefonoCliente.SelectionLength = 0;
            this.txt_telefonoCliente.SelectionStart = 0;
            this.txt_telefonoCliente.ShortcutsEnabled = true;
            this.txt_telefonoCliente.Size = new System.Drawing.Size(190, 27);
            this.txt_telefonoCliente.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txt_telefonoCliente.TabIndex = 59;
            this.txt_telefonoCliente.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_telefonoCliente.TextMarginBottom = 0;
            this.txt_telefonoCliente.TextMarginLeft = 3;
            this.txt_telefonoCliente.TextMarginTop = 1;
            this.txt_telefonoCliente.TextPlaceholder = "";
            this.txt_telefonoCliente.UseSystemPasswordChar = false;
            this.txt_telefonoCliente.WordWrap = true;
            // 
            // txt_correoCliente
            // 
            this.txt_correoCliente.AcceptsReturn = false;
            this.txt_correoCliente.AcceptsTab = false;
            this.txt_correoCliente.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txt_correoCliente.AnimationSpeed = 200;
            this.txt_correoCliente.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_correoCliente.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_correoCliente.AutoSizeHeight = true;
            this.txt_correoCliente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_correoCliente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_correoCliente.BackgroundImage")));
            this.txt_correoCliente.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_correoCliente.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_correoCliente.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_correoCliente.BorderColorIdle = System.Drawing.Color.White;
            this.txt_correoCliente.BorderRadius = 1;
            this.txt_correoCliente.BorderThickness = 2;
            this.txt_correoCliente.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_correoCliente.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_correoCliente.DefaultFont = new System.Drawing.Font("Montserrat", 11F);
            this.txt_correoCliente.DefaultText = "";
            this.txt_correoCliente.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_correoCliente.ForeColor = System.Drawing.Color.White;
            this.txt_correoCliente.HideSelection = true;
            this.txt_correoCliente.IconLeft = null;
            this.txt_correoCliente.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_correoCliente.IconPadding = 10;
            this.txt_correoCliente.IconRight = null;
            this.txt_correoCliente.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_correoCliente.Lines = new string[0];
            this.txt_correoCliente.Location = new System.Drawing.Point(11, 223);
            this.txt_correoCliente.MaxLength = 20;
            this.txt_correoCliente.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_correoCliente.Modified = false;
            this.txt_correoCliente.Multiline = false;
            this.txt_correoCliente.Name = "txt_correoCliente";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_correoCliente.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.White;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_correoCliente.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_correoCliente.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.White;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_correoCliente.OnIdleState = stateProperties24;
            this.txt_correoCliente.Padding = new System.Windows.Forms.Padding(3);
            this.txt_correoCliente.PasswordChar = '\0';
            this.txt_correoCliente.PlaceholderForeColor = System.Drawing.Color.White;
            this.txt_correoCliente.PlaceholderText = "";
            this.txt_correoCliente.ReadOnly = false;
            this.txt_correoCliente.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_correoCliente.SelectedText = "";
            this.txt_correoCliente.SelectionLength = 0;
            this.txt_correoCliente.SelectionStart = 0;
            this.txt_correoCliente.ShortcutsEnabled = true;
            this.txt_correoCliente.Size = new System.Drawing.Size(190, 27);
            this.txt_correoCliente.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txt_correoCliente.TabIndex = 58;
            this.txt_correoCliente.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_correoCliente.TextMarginBottom = 0;
            this.txt_correoCliente.TextMarginLeft = 3;
            this.txt_correoCliente.TextMarginTop = 1;
            this.txt_correoCliente.TextPlaceholder = "";
            this.txt_correoCliente.UseSystemPasswordChar = false;
            this.txt_correoCliente.WordWrap = true;
            // 
            // txt_nombreCliente
            // 
            this.txt_nombreCliente.AcceptsReturn = false;
            this.txt_nombreCliente.AcceptsTab = false;
            this.txt_nombreCliente.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txt_nombreCliente.AnimationSpeed = 200;
            this.txt_nombreCliente.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_nombreCliente.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_nombreCliente.AutoSizeHeight = true;
            this.txt_nombreCliente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_nombreCliente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_nombreCliente.BackgroundImage")));
            this.txt_nombreCliente.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_nombreCliente.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_nombreCliente.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_nombreCliente.BorderColorIdle = System.Drawing.Color.White;
            this.txt_nombreCliente.BorderRadius = 1;
            this.txt_nombreCliente.BorderThickness = 2;
            this.txt_nombreCliente.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_nombreCliente.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_nombreCliente.DefaultFont = new System.Drawing.Font("Montserrat", 11F);
            this.txt_nombreCliente.DefaultText = "";
            this.txt_nombreCliente.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_nombreCliente.ForeColor = System.Drawing.Color.White;
            this.txt_nombreCliente.HideSelection = true;
            this.txt_nombreCliente.IconLeft = null;
            this.txt_nombreCliente.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_nombreCliente.IconPadding = 10;
            this.txt_nombreCliente.IconRight = null;
            this.txt_nombreCliente.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_nombreCliente.Lines = new string[0];
            this.txt_nombreCliente.Location = new System.Drawing.Point(11, 158);
            this.txt_nombreCliente.MaxLength = 20;
            this.txt_nombreCliente.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_nombreCliente.Modified = false;
            this.txt_nombreCliente.Multiline = false;
            this.txt_nombreCliente.Name = "txt_nombreCliente";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_nombreCliente.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.White;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_nombreCliente.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_nombreCliente.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.White;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            stateProperties28.ForeColor = System.Drawing.Color.White;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_nombreCliente.OnIdleState = stateProperties28;
            this.txt_nombreCliente.Padding = new System.Windows.Forms.Padding(3);
            this.txt_nombreCliente.PasswordChar = '\0';
            this.txt_nombreCliente.PlaceholderForeColor = System.Drawing.Color.White;
            this.txt_nombreCliente.PlaceholderText = "";
            this.txt_nombreCliente.ReadOnly = false;
            this.txt_nombreCliente.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_nombreCliente.SelectedText = "";
            this.txt_nombreCliente.SelectionLength = 0;
            this.txt_nombreCliente.SelectionStart = 0;
            this.txt_nombreCliente.ShortcutsEnabled = true;
            this.txt_nombreCliente.Size = new System.Drawing.Size(190, 27);
            this.txt_nombreCliente.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txt_nombreCliente.TabIndex = 57;
            this.txt_nombreCliente.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_nombreCliente.TextMarginBottom = 0;
            this.txt_nombreCliente.TextMarginLeft = 3;
            this.txt_nombreCliente.TextMarginTop = 1;
            this.txt_nombreCliente.TextPlaceholder = "";
            this.txt_nombreCliente.UseSystemPasswordChar = false;
            this.txt_nombreCliente.WordWrap = true;
            // 
            // txt_identCliente
            // 
            this.txt_identCliente.AcceptsReturn = false;
            this.txt_identCliente.AcceptsTab = false;
            this.txt_identCliente.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txt_identCliente.AnimationSpeed = 200;
            this.txt_identCliente.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_identCliente.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_identCliente.AutoSizeHeight = true;
            this.txt_identCliente.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_identCliente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_identCliente.BackgroundImage")));
            this.txt_identCliente.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_identCliente.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_identCliente.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_identCliente.BorderColorIdle = System.Drawing.Color.White;
            this.txt_identCliente.BorderRadius = 1;
            this.txt_identCliente.BorderThickness = 2;
            this.txt_identCliente.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_identCliente.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_identCliente.DefaultFont = new System.Drawing.Font("Montserrat", 11F);
            this.txt_identCliente.DefaultText = "";
            this.txt_identCliente.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.txt_identCliente.ForeColor = System.Drawing.Color.White;
            this.txt_identCliente.HideSelection = true;
            this.txt_identCliente.IconLeft = null;
            this.txt_identCliente.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_identCliente.IconPadding = 10;
            this.txt_identCliente.IconRight = null;
            this.txt_identCliente.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_identCliente.Lines = new string[0];
            this.txt_identCliente.Location = new System.Drawing.Point(11, 90);
            this.txt_identCliente.MaxLength = 20;
            this.txt_identCliente.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_identCliente.Modified = false;
            this.txt_identCliente.Multiline = false;
            this.txt_identCliente.Name = "txt_identCliente";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_identCliente.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.White;
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_identCliente.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(38)))), ((int)(((byte)(59)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_identCliente.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.White;
            stateProperties32.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            stateProperties32.ForeColor = System.Drawing.Color.White;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_identCliente.OnIdleState = stateProperties32;
            this.txt_identCliente.Padding = new System.Windows.Forms.Padding(3);
            this.txt_identCliente.PasswordChar = '\0';
            this.txt_identCliente.PlaceholderForeColor = System.Drawing.Color.White;
            this.txt_identCliente.PlaceholderText = "";
            this.txt_identCliente.ReadOnly = false;
            this.txt_identCliente.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_identCliente.SelectedText = "";
            this.txt_identCliente.SelectionLength = 0;
            this.txt_identCliente.SelectionStart = 0;
            this.txt_identCliente.ShortcutsEnabled = true;
            this.txt_identCliente.Size = new System.Drawing.Size(190, 27);
            this.txt_identCliente.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txt_identCliente.TabIndex = 56;
            this.txt_identCliente.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_identCliente.TextMarginBottom = 0;
            this.txt_identCliente.TextMarginLeft = 3;
            this.txt_identCliente.TextMarginTop = 1;
            this.txt_identCliente.TextPlaceholder = "";
            this.txt_identCliente.UseSystemPasswordChar = false;
            this.txt_identCliente.WordWrap = true;
            // 
            // label4
            // 
            this.label4.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(27)))), ((int)(((byte)(42)))));
            this.label4.Location = new System.Drawing.Point(11, 262);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(68, 20);
            this.label4.TabIndex = 55;
            this.label4.Text = "Teléfono";
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(27)))), ((int)(((byte)(42)))));
            this.label3.Location = new System.Drawing.Point(11, 196);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(57, 20);
            this.label3.TabIndex = 54;
            this.label3.Text = "Correo";
            // 
            // label2
            // 
            this.label2.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(27)))), ((int)(((byte)(42)))));
            this.label2.Location = new System.Drawing.Point(11, 64);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(105, 20);
            this.label2.TabIndex = 53;
            this.label2.Text = "Identificación";
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(27)))), ((int)(((byte)(42)))));
            this.label1.Location = new System.Drawing.Point(11, 130);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(67, 20);
            this.label1.TabIndex = 52;
            this.label1.Text = "Nombre";
            // 
            // label5
            // 
            this.label5.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(27)))), ((int)(((byte)(42)))));
            this.label5.Location = new System.Drawing.Point(11, 327);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(59, 20);
            this.label5.TabIndex = 60;
            this.label5.Text = "Doctor";
            // 
            // cmb_Doctor
            // 
            this.cmb_Doctor.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.cmb_Doctor.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.cmb_Doctor.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmb_Doctor.Font = new System.Drawing.Font("Montserrat", 9F);
            this.cmb_Doctor.ForeColor = System.Drawing.Color.White;
            this.cmb_Doctor.FormattingEnabled = true;
            this.cmb_Doctor.Items.AddRange(new object[] {
            "Activo",
            "No Activo"});
            this.cmb_Doctor.Location = new System.Drawing.Point(11, 359);
            this.cmb_Doctor.Name = "cmb_Doctor";
            this.cmb_Doctor.Size = new System.Drawing.Size(182, 24);
            this.cmb_Doctor.TabIndex = 61;
            // 
            // dtp_fechaCita
            // 
            this.dtp_fechaCita.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.dtp_fechaCita.BackColor = System.Drawing.Color.Transparent;
            this.dtp_fechaCita.BorderColor = System.Drawing.Color.Transparent;
            this.dtp_fechaCita.BorderRadius = 0;
            this.dtp_fechaCita.CalendarFont = new System.Drawing.Font("Montserrat", 11F);
            this.dtp_fechaCita.CalendarForeColor = System.Drawing.Color.White;
            this.dtp_fechaCita.CalendarMonthBackground = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.dtp_fechaCita.Color = System.Drawing.Color.Transparent;
            this.dtp_fechaCita.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtp_fechaCita.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtp_fechaCita.DisabledColor = System.Drawing.Color.Gray;
            this.dtp_fechaCita.DisplayWeekNumbers = false;
            this.dtp_fechaCita.DPHeight = 0;
            this.dtp_fechaCita.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtp_fechaCita.FillDatePicker = false;
            this.dtp_fechaCita.Font = new System.Drawing.Font("Montserrat", 10F);
            this.dtp_fechaCita.ForeColor = System.Drawing.Color.White;
            this.dtp_fechaCita.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtp_fechaCita.Icon = ((System.Drawing.Image)(resources.GetObject("dtp_fechaCita.Icon")));
            this.dtp_fechaCita.IconColor = System.Drawing.Color.White;
            this.dtp_fechaCita.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtp_fechaCita.LeftTextMargin = 5;
            this.dtp_fechaCita.Location = new System.Drawing.Point(11, 414);
            this.dtp_fechaCita.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtp_fechaCita.Name = "dtp_fechaCita";
            this.dtp_fechaCita.Size = new System.Drawing.Size(118, 32);
            this.dtp_fechaCita.TabIndex = 63;
            this.dtp_fechaCita.Value = new System.DateTime(2021, 11, 26, 0, 0, 0, 0);
            // 
            // dtp_horaCita
            // 
            this.dtp_horaCita.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.dtp_horaCita.CalendarFont = new System.Drawing.Font("Montserrat", 9F);
            this.dtp_horaCita.Format = System.Windows.Forms.DateTimePickerFormat.Time;
            this.dtp_horaCita.Location = new System.Drawing.Point(149, 421);
            this.dtp_horaCita.Name = "dtp_horaCita";
            this.dtp_horaCita.ShowUpDown = true;
            this.dtp_horaCita.Size = new System.Drawing.Size(92, 20);
            this.dtp_horaCita.TabIndex = 64;
            this.dtp_horaCita.Value = new System.DateTime(2021, 11, 26, 18, 3, 0, 0);
            // 
            // FormCitas
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(141)))), ((int)(((byte)(169)))));
            this.ClientSize = new System.Drawing.Size(800, 495);
            this.Controls.Add(this.dtp_horaCita);
            this.Controls.Add(this.dtp_fechaCita);
            this.Controls.Add(this.cmb_Doctor);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.txt_telefonoCliente);
            this.Controls.Add(this.txt_correoCliente);
            this.Controls.Add(this.txt_nombreCliente);
            this.Controls.Add(this.txt_identCliente);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.panel1);
            this.Name = "FormCitas";
            this.Text = "Citas";
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgv_doctores)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_eliminarDoctor;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_modificarDoctor;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_buscarDoctor;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_registro;
        private Bunifu.UI.WinForms.BunifuDataGridView dgv_doctores;
        private Bunifu.UI.WinForms.BunifuTextBox txt_telefonoCliente;
        private Bunifu.UI.WinForms.BunifuTextBox txt_correoCliente;
        private Bunifu.UI.WinForms.BunifuTextBox txt_nombreCliente;
        private Bunifu.UI.WinForms.BunifuTextBox txt_identCliente;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.ComboBox cmb_Doctor;
        private Bunifu.UI.WinForms.BunifuDatePicker dtp_fechaCita;
        private System.Windows.Forms.DateTimePicker dtp_horaCita;
    }
}